05 01 file server get
js-tasks-ru/nodejs-20210126_zheka-fateev pull request #3
Opened 2021-02-14 22:04 UTC by Deadlift3008

2021-02-14 22:04 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-02-15 09:16 UTC, tadjik1 commented on 05-http-server-streams/01-file-server-get/server.js
> +      fs.access(filepath, fs.F_OK, (err) => {
здесь не нужно делать проверку таким образом - в начале занятия я рассказывал про принцип атомарности, и тот факт, что любые проверки (access, stat, exists) не дадут гарантии наличия файла в момент createReadStream().

2021-02-15 09:16 UTC, tadjik1 requested changes
@Deadlift3008 нужно исправить момент с проверкой наличия файла. нужно сразу начинать читать файл и обрабатывать "error" на объекте стрима.

2021-02-15 18:09 UTC, Deadlift3008 commented
@tadjik1 поправил. Посмотрите, плз

2021-02-15 18:59 UTC, tadjik1 approved these changes
@Deadlift3008 всё супер!

2021-02-15 18:59 UTC, merged